### PR TITLE
72 delete user

### LINKED ISSUE #72: Delete user
As a user I want to be able to delete my account:
- ✔ through a backend API: HTTP DELETE /close-account where I provide username and password in the request body
- through the website: have a button "Delete account" in the Settings page

✔ As I developer I want to see Postman tests for user deletion:
✔ - Trying to delete a non-existing user
✔ - Trying to delete a user without providing a password
✔ - Correctly deleting a user
✔   - Checking if the user is really deleted: 1) try to sign in with a user first, should succeed; 2) delete the user; 3) try to log in again, should fail

### PR DESCRIPTION
**Pull request by strazdinsg**
Implement user account deletion on backend (endpoint `/close-account`) and on frontend (Settings page). 
Closes #72 
Also - Material UI library added to the frontend project.
Postman tests added

### CODE REVIEW

**Comment by strazdinsg** [comment]
Hmm, I'm wondering, what is the reason for 403? Maybe you have a JWT in cookies which is expired?
The only thing I changed in security config is adding this line:
`.antMatchers("/close-account").permitAll()`

**Comment by jKm00** [comment]
> Hmm, I'm wondering, what is the reason for 403? Maybe you have a JWT in cookies which is expired? The only thing I changed in security config is adding this line: `.antMatchers("/close-account").permitAll()`

Ah, yeah, cookie from somewhere else. Works when deleted

**Review by jKm00 — CHANGES_REQUESTED** [review]
- When deleting account, you are promted with question "Use Google's location service?". Guess this should be something like "Do you really want to delete your account?".
- Also maybe redirect to signin page when user is deleted?

**Comment by strazdinsg** [comment]
Good point! I will fix the "Google's location service" :)
Regarding the sign-in - the user is signed out (and hence redirected to sign-in page) when the snackbar is closed.

**Review by jKm00 — APPROVED** [review]

**Pull request merged**
